### ISSUE TITLE
兄弟能不能给我一份数据，这样就能部署到服务器上

### ISSUE THREAD

**Issue by mialrr** [Mark9804/huazhu_data#3]
兄弟能不能给我一份数据，这样就能部署到服务器上 暗网不会呀

**Comment by Mark9804** [comment]
本来是放上了数据，但是后来想想，这样等于我变成了扩散他人隐私的帮凶，这和我最初写这个脚本的初衷差太多了，所以抱歉，因为用途未知，不能给，见谅。
