### ISSUE TITLE
想问下暗网网站能发下吗。自己去找

### ISSUE THREAD

**Issue by Reyoo** [Mark9804/huazhu_data#6]

**Comment by Mark9804** [comment]
http://lei6ezsexd4iq2tm.onion

在```huazhu.py```中有提供，时间久了要自己找

**Comment by Reyoo** [comment]
有学习用的vpn可以提供吗。另外洋葱浏览器是否可用



sun7127@126.com
 
发件人： Mark Chen
发送时间： 2018-09-06 10:39
收件人： Mark9804/huazhu_data
抄送： Reyoo; Author
主题： Re: [Mark9804/huazhu_data] 想问下暗网网站能发下吗。自己去找 (#6)
http://lei6ezsexd4iq2tm.onion
在huazhu.py中有提供，时间久了要自己找
